version: 0.2

env:
  variables:
    SOLUTION: .\ChatApp.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.5

phases:
  build:
    commands:
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'
artifacts:
  files:
    - .\ChatApp\bin\Debug\*
